version: '3'

volumes:
  db_vol:
    name: db_vol
    driver: local
    driver_opts:
     type: volume
     o: bind
     device: /home/junhjeon/data/data_db
  wp_vol:
    name: wp_vol
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/junhjeon/data/data_wp
  
services:
  mariadb:
    image: mariadb
    env_file:
      - "./.env"
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - "3306"
    networks:
      - intra
    restart: always
    tty: true
    volumes:
      - db_vol:/var/lib/mysql

  wordpress:
    image: wordpress
    env_file:
      - "./.env"
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - intra
    expose:
      - "9000"
    restart: always
    volumes:
      - wp_vol:/var/www/html
    tty: true
    depends_on:
      - mariadb

  nginx:
    image: nginx
    env_file:
      - "./.env"
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - intra
    ports:
      - "443:443"
    volumes:
      - wp_vol:/var/www/html
    restart: always
    tty: true
    depends_on:
      - wordpress

networks:
  intra:
    driver: bridge
